// spec-sha256: a5d9c83422beb5aa159aca8743690eb1dee867b1e07314eab5f8511e3291465d
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whether the demo login helpers are on.
         * @description demo_login is true when the API runs with DEMO_LOGIN=1. The login screen shows the customer search and the random pick only then.
         */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Demo helper. Search the loaded customers, or pick one with an email at random.
         * @description Only with DEMO_LOGIN=1; not found otherwise. It fills the login form and never opens a session. Send q or random=true, not both and not neither. With q, at most 20 rows matching name, document number, or customer_id, ordered by last_name, first_name, customer_id ascending. With random=true, one customer with an email on file. Any customer in gold can be found. The four oracle profiles are not an allowlist.
         */
        get: operations["searchCustomers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a 6-digit code to the customer with this document number.
         * @description When document_number matches a customer with an email on file, a code valid for 10 minutes is stored as a hash and emailed to that address, written in locale. A new request replaces any unused code for the same customer. The response is the same whether or not the document matches and whether or not the customer has an email. It never carries the code, the address, or the name.
         */
        post: operations["requestCustomerCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a document number and its emailed code for a JWT.
         * @description Claims inside the token are sub = customer_id, role = customer, exp 15 minutes. The body repeats sub and role so the client can route without decoding the token. The code must be the latest unused one for the customer with this document number, under 10 minutes old, with fewer than 5 wrong tries. The fifth wrong code spends it. A used code does not open a second session. Every failure is the same unauthorized answer. An expired token on a later call is 401. The session is not renewed.
         */
        post: operations["openCustomerSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultants/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Demo helper. Search the active consultants, or pick one at random.
         * @description Only with DEMO_LOGIN=1; not found otherwise. It fills the consultant login form and never opens a session. Send q or random=true, not both and not neither. Only consultants whose service_agents.agent_status is Active are listed, because only they can receive a code. With q, at most 20 rows matching name, employee code, or consultant_id, ordered by last_name, first_name, consultant_id ascending. With random=true, one active consultant.
         */
        get: operations["searchConsultants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultant/session/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a 6-digit code to the active consultant with this email and employee code.
         * @description Spaces around either field are ignored, the email is compared in lower case, and the employee code in upper case. When the pair matches a consultant whose service_agents.agent_status is Active, a code valid for 10 minutes is stored as a hash and emailed to that address, written in locale. A new request replaces any unused code for the same consultant. The response is the same for every pair and every status. It never carries the code, the address, or the name.
         */
        post: operations["requestConsultantCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultant/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange an email, an employee code, and the emailed code for a JWT.
         * @description Claims inside the token are sub = consultant_id, role = consultant, exp 15 minutes. The pair is matched as on the code request and must still belong to an active consultant. The code must be the latest unused one for that consultant, under 10 minutes old, with fewer than 5 wrong tries. The fifth wrong code spends it. A used code does not open a second session. A customer code does not open a consultant session. Every failure is the same unauthorized answer.
         */
        post: operations["openConsultantSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The session customer's id and name.
         * @description Requires role customer. customer_id is the token sub. The app bar and the home greeting read the name from here; the login responses never carry it.
         */
        get: operations["getCurrentCustomer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Products of the customer in the JWT, in the currency stored on the row.
         * @description Requires role customer. A consultant token is forbidden. customer_id is optional. If it is absent, or equal to the token sub, the response is that customer's products. If it is any other id, the response is an empty list. Balances are not converted. Products whose product_status is Closed are left out, and so are loans (Préstamo Personal, Préstamo Hipotecario) whose balance is 0, which are paid. Their status in the data is not changed. Order is product_id ascending. days_past_due, credit_limit, and interest_rate are not on this response.
         */
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Append the customer's message and return the case after that cycle's commands finish.
         * @description Requires role customer. The body is text, client_message_id, locale (the language chosen with the switch), and exactly one of product or process_id (PLAN.md D24). product starts a case for that product: the customer confirmed it in the start dialog, which is the consent, and the policy runs at once. process_id sends the message to that case of the token's customer. Neither or both is 422. Alba's reply, templates, and certificate for this case are written in the locale of the latest message. customer_id comes from the token; the customer never sends process_state. The handler appends conversation.message_received. It does not choose an outcome. The response is sent after the worker has finished the commands enqueued from that event. If they have not finished within 30 seconds, the answer is 503 cycle_pending and nothing is undone: the same client_message_id sent again waits for the same cycle. The same client_message_id with the same text, locale, and product from the same customer returns this case again and does not append a second event. The same client_message_id for another message is 409 message_id_reused and appends nothing. A start for a product that already has an open case is 409 case_already_open, also when another start for the product opened its case first. A message to an ended case is 409 case_ended. Another customer's process_id, or an unknown one, is 404.
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The session customer's cases, newest first.
         * @description Requires role customer. Every process of the token's customer, open or ended, newest first (PLAN.md D17, D24). The home shows each product's latest case: an open one to continue, an ended one to see its result.
         */
        get: operations["listCases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case/{process_id}/appeal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask a person to review a no the policy decided, which reopens the case for a consultant.
         * @description Requires role customer (PLAN.md D25). The case must be the token's customer's, ended as not_prequalified by the policy, and not appealed before; otherwise 409 case_not_appealable, or 404 for another customer's or an unknown case. While another case of the same product is open, the case cannot reopen: 409 case_already_open. Case.appealable says in advance whether this succeeds. Appends conversation.appeal_requested, keyed appeal:{process_id}; the case moves back to human_active with reason customer_requested_human and the customer gets the referral notice. Sending it again for the same case returns the case and appends nothing. The response is the case after that cycle, or 503 cycle_pending as for POST /messages.
         */
        post: operations["appealCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case/{process_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The customer's thread and certificate for one process.
         * @description Requires role customer. The process must belong to the token sub. Another customer's process, or an unknown id, is not found.
         */
        get: operations["getCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultant/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The session consultant's id, employee code, name, and specialty.
         * @description Requires role consultant. consultant_id is the token sub. specialty is null when the file has none. The consultant screens read the name from here; the login responses never carry it.
         */
        get: operations["getCurrentConsultant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultant/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Processes in human_active.
         * @description Requires role consultant. Ended and ai_active processes are not listed. Order is processes.created_at ascending, then process id ascending.
         */
        get: operations["listConsultantQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultant/case/{process_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Handoff packet for a process in human_active.
         * @description Requires role consultant. A process that is not human_active is not found. Packet fields that come from the case's latest analysis.completed are null when that event does not exist (a handoff before the policy ran). closable says whether the case may be closed. There is no text field and no reply body.
         */
        get: operations["getConsultantCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultant/case/{process_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The process events, in the order they were recorded.
         * @description Requires role consultant. Included events are those whose process_id is this process, plus each conversation.message_received with a null process_id that an event of this process names in caused_by_event_id: the opening message through process.started, and a message sent before the case existed that joined it. A message no event names is not attached by time. Order is the order the events were written (events.seq).
         */
        get: operations["getConsultantCaseTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultant/case/{process_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close a human_active case as pre-qualified or not.
         * @description Requires role consultant. outcome is PREQUALIFIED or NOT_PREQUALIFIED. Any other outcome, or a text field, is invalid_body. There is no reply. The handler appends conversation.consultant_closed. It does not run the policy. A second close of the same process is already_closed and does not append another event. A process that is not human_active is not found, except a process already ended, which is already_closed. A case whose latest analysis.completed is missing or NEEDS_INFO is case_not_closable (PLAN.md D15 (3)). The response is sent after the worker finishes the close's commands, or cycle_pending after 30 seconds.
         */
        post: operations["closeConsultantCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        ReadyOk: {
            /** @enum {string} */
            status: "ready";
        };
        ReadyDown: {
            /** @enum {string} */
            status: "not_ready";
            /** @description Exception class name. Not a customer-facing sentence. */
            error: string;
        };
        UnauthorizedError: {
            /** @enum {string} */
            error: "unauthorized";
        };
        ForbiddenError: {
            /** @enum {string} */
            error: "forbidden";
        };
        NotFoundError: {
            /** @enum {string} */
            error: "not_found";
        };
        MessageIdReusedError: {
            /** @enum {string} */
            error: "message_id_reused";
        };
        CaseConflictError: {
            /** @enum {string} */
            error: "case_already_open" | "case_ended" | "case_not_appealable" | "case_not_closable";
        };
        CyclePendingError: {
            /** @enum {string} */
            error: "cycle_pending";
        };
        AlreadyClosedError: {
            /** @enum {string} */
            error: "already_closed";
        };
        InvalidRequestError: {
            /** @enum {string} */
            error: "invalid_body";
        };
        /** @enum {string} */
        Role: "customer" | "consultant";
        /**
         * @description The language chosen with the switch in the app bar (PLAN.md D21, D22). Alba writes in it: the screens, the login email, replies, templates, and the certificate. Spanish and Portuguese only, as the brief asks.
         * @enum {string}
         */
        Locale: "es" | "pt";
        /** @enum {string} */
        ProcessState: "ai_active" | "human_active" | "ended";
        /** @enum {string} */
        EndReason: "prequalified" | "not_prequalified";
        /** @enum {string} */
        ProductKey: "credit_card" | "personal_loan";
        /**
         * @description What the model read in the customer's text. It only decides whether Alba can read the message: other, English included, hands the case to a person (PLAN.md D22). Alba writes in the message's locale, not in this language. A turn whose language differs from its locale is kept as it is and counted in the multilingual-ambiguity evaluation.
         * @enum {string}
         */
        TurnLanguage: "es" | "pt" | "other";
        /** @enum {string} */
        Outcome: "PREQUALIFIED" | "NOT_PREQUALIFIED" | "REFER" | "NEEDS_INFO";
        /** @enum {string} */
        CloseOutcome: "PREQUALIFIED" | "NOT_PREQUALIFIED";
        /** @enum {string} */
        IncomeCurrency: "MXN" | "COP" | "ARS";
        /** @enum {string} */
        ReasonCode: "customer_requested_human" | "out_of_scope" | "language_unsupported" | "model_output_invalid" | "tool_failed" | "policy_refer" | "reply_forbidden";
        /** @enum {string} */
        Intent: "product_info" | "prequalify_card" | "prequalify_loan" | "confirm_prequalify" | "decline_prequalify" | "provide_income" | "human_request" | "out_of_scope" | "clarify" | "chit_chat";
        /** @enum {string} */
        TemplateId: "needs_income" | "refer_notice" | "which_product" | "confirm_prequalify" | "product_case_open";
        /** @enum {string} */
        DecidedBy: "policy" | "consultant";
        /** @enum {string} */
        RuleId: "R01" | "R02" | "R03" | "R04" | "R05" | "R06" | "R09";
        /** @enum {string} */
        RuleTraceResult: "passed" | "self_declared" | "PREQUALIFIED" | "NOT_PREQUALIFIED" | "REFER" | "NEEDS_INFO";
        /** @enum {string} */
        Actor: "customer" | "consultant" | "system" | "rule";
        /** @enum {string} */
        MessageAuthor: "customer" | "assistant" | "template";
        /** @enum {string} */
        PolicyVersion: "alba-credit-v1";
        /** @enum {string} */
        ProcessKey: "credit_prequalification";
        /** @enum {string} */
        EventName: "conversation.message_received" | "conversation.turn_classified" | "conversation.template_sent" | "conversation.consultant_closed" | "conversation.thread_taken" | "analysis.completed" | "prequalification.decided" | "process.started" | "process.state_changed" | "process.ended" | "conversation.appeal_requested";
        Config: {
            demo_login: boolean;
        };
        CustomerSearchHit: {
            customer_id: string;
            document_number: string;
            first_name: string;
            last_name: string;
            country: string;
        };
        CustomerSearchResults: {
            customers: components["schemas"]["CustomerSearchHit"][];
        };
        ConsultantSearchHit: {
            consultant_id: string;
            employee_code: string;
            first_name: string;
            last_name: string;
            email: string;
        };
        ConsultantSearchResults: {
            consultants: components["schemas"]["ConsultantSearchHit"][];
        };
        RequestCustomerCode: {
            document_number: string;
            locale: components["schemas"]["Locale"];
        };
        CodeRequested: {
            /**
             * @description How long a sent code is valid. The same value whether or not a code was sent.
             * @enum {integer}
             */
            expires_in_seconds: 600;
        };
        OpenCustomerSessionRequest: {
            document_number: string;
            code: string;
        };
        RequestConsultantCode: {
            email: string;
            employee_code: string;
            locale: components["schemas"]["Locale"];
        };
        OpenConsultantSessionRequest: {
            email: string;
            employee_code: string;
            code: string;
        };
        Session: {
            token: string;
            /** @description customer_id or consultant_id, the same value as the token sub claim. */
            sub: string;
            role: components["schemas"]["Role"];
        };
        CurrentCustomer: {
            customer_id: string;
            first_name: string;
            last_name: string;
        };
        CurrentConsultant: {
            consultant_id: string;
            employee_code: string;
            first_name: string;
            last_name: string;
            specialty: string | null;
        };
        Product: {
            product_id: string;
            /** @description Dataset literal as stored, for example Tarjeta Crédito. Not translated. */
            product_type: string;
            product_number: string;
            /** @description The products.currency value. Not converted. */
            currency: string;
            current_balance: number;
            product_status: string;
        };
        ProductList: {
            products: components["schemas"]["Product"][];
        };
        SendMessageRequest: {
            text: string;
            /**
             * Format: uuid
             * @description One id per send. The idempotency key is msg:{client_message_id}.
             */
            client_message_id: string;
            locale: components["schemas"]["Locale"];
            /** @description Starts a case for this product, confirmed in the start dialog (the consent). Not with process_id. */
            product?: components["schemas"]["ProductKey"];
            /**
             * Format: uuid
             * @description The case this message belongs to. Not with product.
             */
            process_id?: string;
        };
        ThreadMessage: {
            /** Format: uuid */
            id: string;
            author: components["schemas"]["MessageAuthor"];
            body: string;
            /** Format: uuid */
            event_id: string;
        };
        /** @description The latest prequalification.decided of this process. A policy certificate copies its income fields from the facts (income_local, income_currency, income_usd) of the analysis.completed its decision names in caused_by_event_id, and its product from that analysis; as_of is the as_of of the income_local fact. A consultant certificate is the person's decision: its income fields and as_of are null and its product is the case's (PLAN.md D25). This object has no credit limit and no interest rate. */
        Certificate: {
            /**
             * Format: uuid
             * @description The prequalification.decided event; its messages row places the certificate in the thread (D25).
             */
            event_id: string;
            decided_by: components["schemas"]["DecidedBy"];
            locale: components["schemas"]["Locale"];
            outcome: components["schemas"]["CloseOutcome"];
            body: string;
            product: components["schemas"]["ProductKey"] | null;
            income_local: number | null;
            income_currency: components["schemas"]["IncomeCurrency"] | null;
            income_usd: number | null;
            /** Format: date */
            as_of: string | null;
        };
        AppealRequest: {
            locale: components["schemas"]["Locale"];
        };
        CaseSummary: {
            /** Format: uuid */
            process_id: string;
            product: components["schemas"]["ProductKey"] | null;
            state: components["schemas"]["ProcessState"];
            end_reason: components["schemas"]["EndReason"] | null;
            locale: components["schemas"]["Locale"];
        };
        CaseList: {
            cases: components["schemas"]["CaseSummary"][];
        };
        /** @description messages is the thread. Customer lines come from conversation.message_received events that belong to the process, plus each such event with a null process_id that an event of the process names in caused_by_event_id (the opening message through process.started, and a message sent before the case existed that joined it). Assistant and template lines come from messages rows. A messages row with a null event_id is omitted. Order is the order the linked events were written (events.seq). certificate is null until prequalification.decided exists. appealable is true only when the certificate is a no the policy decided, the case has ended, and no other case of its product is open (PLAN.md D25); the screen offers the review only then. */
        Case: {
            /** Format: uuid */
            process_id: string;
            state: components["schemas"]["ProcessState"];
            end_reason: components["schemas"]["EndReason"] | null;
            product: components["schemas"]["ProductKey"] | null;
            locale: components["schemas"]["Locale"];
            messages: components["schemas"]["ThreadMessage"][];
            certificate: components["schemas"]["Certificate"] | null;
            appealable: boolean;
        };
        ConsultantQueueItem: {
            /** Format: uuid */
            process_id: string;
            customer_id: string;
            first_name: string;
            last_name: string;
            product: components["schemas"]["ProductKey"] | null;
            reason_code: components["schemas"]["ReasonCode"];
            locale: components["schemas"]["Locale"];
        };
        ConsultantQueue: {
            cases: components["schemas"]["ConsultantQueueItem"][];
        };
        /** @description The handoff packet. product, credit_score, the income fields, deciding_rule, policy_version, and outcome are copied from the case's latest analysis.completed. They are null when that event does not exist. reason_code is copied from the latest conversation.thread_taken. closable is true only when that analysis exists and its outcome is not NEEDS_INFO (PLAN.md D15 (3)). */
        ConsultantCase: {
            /** Format: uuid */
            process_id: string;
            /** @enum {string} */
            state: "human_active";
            customer_id: string;
            first_name: string;
            last_name: string;
            product: components["schemas"]["ProductKey"] | null;
            credit_score: number | null;
            income_local: number | null;
            income_currency: components["schemas"]["IncomeCurrency"] | null;
            income_usd: number | null;
            deciding_rule: components["schemas"]["RuleId"] | null;
            policy_version: components["schemas"]["PolicyVersion"] | null;
            outcome: components["schemas"]["Outcome"] | null;
            reason_code: components["schemas"]["ReasonCode"];
            locale: components["schemas"]["Locale"];
            closable: boolean;
        };
        CloseCaseRequest: {
            outcome: components["schemas"]["CloseOutcome"];
        };
        ConsultantCloseResult: {
            /** Format: uuid */
            process_id: string;
            /** @enum {string} */
            state: "ended";
            end_reason: components["schemas"]["EndReason"];
            outcome: components["schemas"]["CloseOutcome"];
        };
        Fact: {
            name: string;
            value: (string | number | boolean) | null;
            source: string;
            /** Format: date */
            as_of: string;
        };
        RuleTraceStep: {
            rule_id: components["schemas"]["RuleId"];
            /** @description Condition snapshot recorded with the step. The trace displays it. No rule matches on it. */
            input: {
                [key: string]: unknown;
            };
            result: components["schemas"]["RuleTraceResult"];
        };
        TraceEventBase: {
            /** Format: uuid */
            id: string;
            event_name: components["schemas"]["EventName"];
            /** Format: date-time */
            created_at: string;
            actor: components["schemas"]["Actor"];
            /** Format: uuid */
            process_id: string | null;
            process_state: components["schemas"]["ProcessState"];
            /** Format: uuid */
            caused_by_event_id: string | null;
        };
        TraceMessageReceived: components["schemas"]["TraceEventBase"] & {
            /** @enum {string} */
            event_name: "conversation.message_received";
            text: string;
            /** Format: uuid */
            client_message_id: string;
            locale: components["schemas"]["Locale"];
            /** @description Set on the message that starts a case from the home (PLAN.md D24); null on every other one. */
            product: components["schemas"]["ProductKey"] | null;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_name: "conversation.message_received";
        };
        TraceTurnClassified: components["schemas"]["TraceEventBase"] & {
            /** @enum {string} */
            event_name: "conversation.turn_classified";
            intent: components["schemas"]["Intent"];
            product: components["schemas"]["ProductKey"] | null;
            language: components["schemas"]["TurnLanguage"];
            locale: components["schemas"]["Locale"];
            declared_income_amount: number | null;
            declared_income_currency: components["schemas"]["IncomeCurrency"] | null;
            reply_text: string;
            reply_ok: boolean;
            reason_code: components["schemas"]["ReasonCode"] | null;
            product_asked_count: number;
            income_requested: boolean;
            /** @description The other product the turn names when that product already has its own open case (D24). */
            open_case_product: components["schemas"]["ProductKey"] | null;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_name: "conversation.turn_classified";
        };
        TraceTemplateSent: components["schemas"]["TraceEventBase"] & {
            /** @enum {string} */
            event_name: "conversation.template_sent";
            locale: components["schemas"]["Locale"];
            template_id: components["schemas"]["TemplateId"];
            body: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_name: "conversation.template_sent";
        };
        TraceConsultantClosed: components["schemas"]["TraceEventBase"] & {
            /** @enum {string} */
            event_name: "conversation.consultant_closed";
            outcome: components["schemas"]["CloseOutcome"];
            consultant_id: string;
            locale: components["schemas"]["Locale"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_name: "conversation.consultant_closed";
        };
        TraceThreadTaken: components["schemas"]["TraceEventBase"] & {
            /** @enum {string} */
            event_name: "conversation.thread_taken";
            reason_code: components["schemas"]["ReasonCode"];
            from_state: components["schemas"]["ProcessState"];
            to_state: components["schemas"]["ProcessState"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_name: "conversation.thread_taken";
        };
        TraceAnalysisCompleted: components["schemas"]["TraceEventBase"] & {
            /** @enum {string} */
            event_name: "analysis.completed";
            policy_version: components["schemas"]["PolicyVersion"];
            product: components["schemas"]["ProductKey"];
            outcome: components["schemas"]["Outcome"];
            deciding_rule: components["schemas"]["RuleId"];
            rule_trace: components["schemas"]["RuleTraceStep"][];
            facts: components["schemas"]["Fact"][];
            locale: components["schemas"]["Locale"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_name: "analysis.completed";
        };
        TracePrequalificationDecided: components["schemas"]["TraceEventBase"] & {
            /** @enum {string} */
            event_name: "prequalification.decided";
            locale: components["schemas"]["Locale"];
            outcome: components["schemas"]["CloseOutcome"];
            body: string;
            decided_by: components["schemas"]["DecidedBy"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_name: "prequalification.decided";
        };
        TraceProcessStarted: components["schemas"]["TraceEventBase"] & {
            /** @enum {string} */
            event_name: "process.started";
            process_key: components["schemas"]["ProcessKey"];
            customer_id: string;
            locale: components["schemas"]["Locale"];
            product: components["schemas"]["ProductKey"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_name: "process.started";
        };
        TraceProcessStateChanged: components["schemas"]["TraceEventBase"] & {
            /** @enum {string} */
            event_name: "process.state_changed";
            from_state: components["schemas"]["ProcessState"];
            to_state: components["schemas"]["ProcessState"];
            end_reason: components["schemas"]["EndReason"] | null;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_name: "process.state_changed";
        };
        TraceProcessEnded: components["schemas"]["TraceEventBase"] & {
            /** @enum {string} */
            event_name: "process.ended";
            end_reason: components["schemas"]["EndReason"];
            policy_version: components["schemas"]["PolicyVersion"] | null;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_name: "process.ended";
        };
        TraceAppealRequested: components["schemas"]["TraceEventBase"] & {
            /** @enum {string} */
            event_name: "conversation.appeal_requested";
            locale: components["schemas"]["Locale"];
            product: components["schemas"]["ProductKey"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_name: "conversation.appeal_requested";
        };
        TraceEvent: components["schemas"]["TraceMessageReceived"] | components["schemas"]["TraceTurnClassified"] | components["schemas"]["TraceTemplateSent"] | components["schemas"]["TraceConsultantClosed"] | components["schemas"]["TraceThreadTaken"] | components["schemas"]["TraceAnalysisCompleted"] | components["schemas"]["TracePrequalificationDecided"] | components["schemas"]["TraceProcessStarted"] | components["schemas"]["TraceProcessStateChanged"] | components["schemas"]["TraceProcessEnded"] | components["schemas"]["TraceAppealRequested"];
        CaseTrace: {
            /** Format: uuid */
            process_id: string;
            events: components["schemas"]["TraceEvent"][];
        };
    };
    responses: {
        /** @description Missing token, expired token, or a code that does not open a session. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["UnauthorizedError"];
            };
        };
        /** @description The token role cannot call this route. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ForbiddenError"];
            };
        };
        /** @description No row for this id under the token's scope. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["NotFoundError"];
            };
        };
        /** @description This client_message_id was already sent with another text or by another customer. Nothing is appended. */
        MessageIdReused: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MessageIdReusedError"];
            };
        };
        /** @description Nothing is appended. message_id_reused: this client_message_id was already sent for another message. case_already_open: the product already has an open case. case_ended: the case has ended. */
        MessageConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MessageIdReusedError"] | components["schemas"]["CaseConflictError"];
            };
        };
        /** @description The message or appeal is stored, and its commands had not finished after 30 seconds. Nothing is undone; the same request sent again waits for the same cycle. */
        CyclePending: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CyclePendingError"];
            };
        };
        /** @description Nothing is appended. already_closed: the process was already ended or closed, and the outcome does not change. case_not_closable: the policy reached no result on this case (PLAN.md D15 (3)). */
        CloseConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AlreadyClosedError"] | components["schemas"]["CaseConflictError"];
            };
        };
        /** @description The body or query does not match the schema. */
        InvalidRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["InvalidRequestError"];
            };
        };
    };
    parameters: {
        OptionalSearchQuery: string;
        RandomPick: true;
        ProcessId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Postgres answered. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOk"];
                };
            };
            /** @description Postgres did not answer. error is the exception class name. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyDown"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
        };
    };
    searchCustomers: {
        parameters: {
            query?: {
                q?: components["parameters"]["OptionalSearchQuery"];
                random?: components["parameters"]["RandomPick"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching customers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerSearchResults"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidRequest"];
        };
    };
    requestCustomerCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCustomerCode"];
            };
        };
        responses: {
            /** @description The request was taken. A code was sent only if the document matched a customer with an email. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeRequested"];
                };
            };
            422: components["responses"]["InvalidRequest"];
        };
    };
    openCustomerSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenCustomerSessionRequest"];
            };
        };
        responses: {
            /** @description Customer session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["InvalidRequest"];
        };
    };
    searchConsultants: {
        parameters: {
            query?: {
                q?: components["parameters"]["OptionalSearchQuery"];
                random?: components["parameters"]["RandomPick"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching active consultants. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultantSearchResults"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidRequest"];
        };
    };
    requestConsultantCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestConsultantCode"];
            };
        };
        responses: {
            /** @description The request was taken. A code was sent only if the pair matched an active consultant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeRequested"];
                };
            };
            422: components["responses"]["InvalidRequest"];
        };
    };
    openConsultantSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenConsultantSessionRequest"];
            };
        };
        responses: {
            /** @description Consultant session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["InvalidRequest"];
        };
    };
    getCurrentCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The customer on the token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentCustomer"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listProducts: {
        parameters: {
            query?: {
                customer_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session customer's products, or an empty list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description The case this message belongs to, after the worker finishes that cycle. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["MessageConflict"];
            422: components["responses"]["InvalidRequest"];
            503: components["responses"]["CyclePending"];
        };
    };
    listCases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The customer's cases. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    appealCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: components["parameters"]["ProcessId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppealRequest"];
            };
        };
        responses: {
            /** @description The case, back with a person. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["MessageConflict"];
            422: components["responses"]["InvalidRequest"];
            503: components["responses"]["CyclePending"];
        };
    };
    getCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: components["parameters"]["ProcessId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thread and certificate. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getCurrentConsultant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The consultant on the token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentConsultant"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listConsultantQueue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The review queue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultantQueue"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getConsultantCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: components["parameters"]["ProcessId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The packet. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultantCase"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getConsultantCaseTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: components["parameters"]["ProcessId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events for this process. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseTrace"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    closeConsultantCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: components["parameters"]["ProcessId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseCaseRequest"];
            };
        };
        responses: {
            /** @description The case is ended with that outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultantCloseResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["CloseConflict"];
            422: components["responses"]["InvalidRequest"];
            503: components["responses"]["CyclePending"];
        };
    };
}
