# spec-sha256: f1180b884d1391c5ff6bab8835e0edd4a13a45eee7c21fe2444052bcd7cd1865
# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from datetime import date
from typing import Annotated, Any, Dict, List, Literal, Optional, Union
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Health(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['ok']


class ReadyOk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['ready']


class ReadyDown(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['not_ready']
    error: Annotated[
        str,
        Field(
            description='Exception class name. Not a customer-facing sentence.',
            min_length=1,
        ),
    ]


class UnauthorizedError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: Literal['unauthorized']


class ForbiddenError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: Literal['forbidden']


class NotFoundError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: Literal['not_found']


class MessageIdReusedError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: Literal['message_id_reused']


class AlreadyClosedError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: Literal['already_closed']


class InvalidRequestError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: Literal['invalid_body']


class Config(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    demo_login: bool


class CustomerSearchHit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    customer_id: str
    document_number: str
    first_name: str
    last_name: str
    country: str


class CustomerSearchResults(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    customers: Annotated[List[CustomerSearchHit], Field(max_length=20)]


class ConsultantSearchHit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    consultant_id: str
    employee_code: str
    first_name: str
    last_name: str
    email: str


class ConsultantSearchResults(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    consultants: Annotated[List[ConsultantSearchHit], Field(max_length=20)]


class RequestCustomerCode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    document_number: Annotated[str, Field(min_length=1)]


class CodeRequested(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expires_in_seconds: Annotated[
        Literal[600],
        Field(
            description='How long a sent code is valid. The same value whether or not a code was sent.'
        ),
    ]


class OpenCustomerSessionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    document_number: Annotated[str, Field(min_length=1)]
    code: Annotated[str, Field(pattern='^[0-9]{6}$')]


class RequestConsultantCode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Annotated[str, Field(min_length=1)]
    employee_code: Annotated[str, Field(min_length=1)]


class OpenConsultantSessionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Annotated[str, Field(min_length=1)]
    employee_code: Annotated[str, Field(min_length=1)]
    code: Annotated[str, Field(pattern='^[0-9]{6}$')]


class Session(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token: str
    sub: Annotated[
        str,
        Field(
            description='customer_id or consultant_id, the same value as the token sub claim.'
        ),
    ]
    role: Literal['customer', 'consultant']


class CurrentCustomer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    customer_id: str
    first_name: str
    last_name: str


class CurrentConsultant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    consultant_id: str
    employee_code: str
    first_name: str
    last_name: str
    specialty: Annotated[Optional[str], Field(...)] = None


class Product(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    product_id: str
    product_type: Annotated[
        str,
        Field(
            description='Dataset literal as stored, for example Tarjeta Crédito. Not translated.'
        ),
    ]
    product_number: str
    currency: Annotated[
        str, Field(description='The products.currency value. Not converted.')
    ]
    current_balance: float
    product_status: str


class ProductList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    products: List[Product]


class SendMessageRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Annotated[str, Field(min_length=1)]
    client_message_id: Annotated[
        UUID,
        Field(
            description='One id per send. The idempotency key is msg:{client_message_id}.'
        ),
    ]


class ThreadMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    author: Literal['customer', 'assistant', 'template']
    body: str
    event_id: UUID


class Certificate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    locale: Literal['es', 'pt']
    outcome: Literal['PREQUALIFIED', 'NOT_PREQUALIFIED']
    body: str
    product: Annotated[Optional[Literal['credit_card', 'personal_loan']], Field(...)]
    income_local: Annotated[Optional[float], Field(...)] = None
    income_currency: Annotated[Optional[Literal['MXN', 'COP', 'ARS']], Field(...)]
    income_usd: Annotated[Optional[float], Field(...)] = None
    as_of: Annotated[Optional[date], Field(...)] = None


class Case(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    process_id: UUID
    state: Literal['ai_active', 'human_active', 'ended']
    end_reason: Annotated[
        Optional[Literal['prequalified', 'not_prequalified']], Field(...)
    ]
    product: Annotated[Optional[Literal['credit_card', 'personal_loan']], Field(...)]
    language: Annotated[Optional[Literal['es', 'pt']], Field(...)]
    messages: List[ThreadMessage]
    certificate: Annotated[Optional[Certificate], Field(...)]


class ConsultantQueueItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    process_id: UUID
    customer_id: str
    first_name: str
    last_name: str
    product: Annotated[Optional[Literal['credit_card', 'personal_loan']], Field(...)]
    reason_code: Literal[
        'customer_requested_human',
        'out_of_scope',
        'language_unsupported',
        'model_output_invalid',
        'tool_failed',
        'policy_refer',
        'reply_forbidden',
    ]
    language: Annotated[Optional[Literal['es', 'pt']], Field(...)]


class ConsultantQueue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cases: List[ConsultantQueueItem]


class ConsultantCase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    process_id: UUID
    state: Literal['human_active']
    customer_id: str
    first_name: str
    last_name: str
    product: Annotated[Optional[Literal['credit_card', 'personal_loan']], Field(...)]
    credit_score: Annotated[Optional[float], Field(...)] = None
    income_local: Annotated[Optional[float], Field(...)] = None
    income_currency: Annotated[Optional[Literal['MXN', 'COP', 'ARS']], Field(...)]
    income_usd: Annotated[Optional[float], Field(...)] = None
    deciding_rule: Annotated[
        Optional[Literal['R01', 'R02', 'R03', 'R04', 'R05', 'R06', 'R09']], Field(...)
    ]
    policy_version: Annotated[Optional[Literal['alba-credit-v1']], Field(...)]
    outcome: Annotated[
        Optional[Literal['PREQUALIFIED', 'NOT_PREQUALIFIED', 'REFER', 'NEEDS_INFO']],
        Field(...),
    ]
    reason_code: Literal[
        'customer_requested_human',
        'out_of_scope',
        'language_unsupported',
        'model_output_invalid',
        'tool_failed',
        'policy_refer',
        'reply_forbidden',
    ]
    language: Annotated[Optional[Literal['es', 'pt']], Field(...)]


class CloseCaseRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outcome: Literal['PREQUALIFIED', 'NOT_PREQUALIFIED']


class ConsultantCloseResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    process_id: UUID
    state: Literal['ended']
    end_reason: Literal['prequalified', 'not_prequalified']
    outcome: Literal['PREQUALIFIED', 'NOT_PREQUALIFIED']


class Fact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    value: Annotated[
        Optional[Union[Optional[str], Optional[float], Optional[bool]]], Field(...)
    ]
    source: str
    as_of: date


class RuleTraceStep(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rule_id: Literal['R01', 'R02', 'R03', 'R04', 'R05', 'R06', 'R09']
    input: Annotated[
        Dict[str, Any],
        Field(
            description='Condition snapshot recorded with the step. The trace displays it. No rule matches on it.'
        ),
    ]
    result: Literal[
        'passed',
        'self_declared',
        'PREQUALIFIED',
        'NOT_PREQUALIFIED',
        'REFER',
        'NEEDS_INFO',
    ]


class TraceEventBase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    event_name: Literal[
        'conversation.message_received',
        'conversation.turn_classified',
        'conversation.template_sent',
        'conversation.consultant_closed',
        'conversation.thread_taken',
        'analysis.completed',
        'prequalification.decided',
        'process.started',
        'process.state_changed',
        'process.ended',
    ]
    created_at: AwareDatetime
    actor: Literal['customer', 'consultant', 'system', 'rule']
    process_id: Annotated[Optional[UUID], Field(...)] = None
    process_state: Literal['ai_active', 'human_active', 'ended']
    caused_by_event_id: Annotated[Optional[UUID], Field(...)] = None


class TraceMessageReceived(TraceEventBase):
    event_name: Literal['conversation.message_received']
    text: str
    client_message_id: UUID


class TraceTurnClassified(TraceEventBase):
    event_name: Literal['conversation.turn_classified']
    intent: Literal[
        'product_info',
        'prequalify_card',
        'prequalify_loan',
        'confirm_prequalify',
        'decline_prequalify',
        'provide_income',
        'human_request',
        'out_of_scope',
        'clarify',
        'chit_chat',
    ]
    product: Annotated[Optional[Literal['credit_card', 'personal_loan']], Field(...)]
    language: Literal['es', 'pt', 'other']
    declared_income_amount: Annotated[Optional[float], Field(...)] = None
    declared_income_currency: Annotated[
        Optional[Literal['MXN', 'COP', 'ARS']], Field(...)
    ]
    reply_text: str
    reply_ok: bool
    reason_code: Annotated[
        Optional[
            Literal[
                'customer_requested_human',
                'out_of_scope',
                'language_unsupported',
                'model_output_invalid',
                'tool_failed',
                'policy_refer',
                'reply_forbidden',
            ]
        ],
        Field(...),
    ]
    product_asked_count: Annotated[int, Field(ge=0)]
    income_requested: bool


class TraceTemplateSent(TraceEventBase):
    event_name: Literal['conversation.template_sent']
    locale: Literal['es', 'pt']
    template_id: Literal[
        'needs_income', 'refer_notice', 'which_product', 'confirm_prequalify'
    ]
    body: str


class TraceConsultantClosed(TraceEventBase):
    event_name: Literal['conversation.consultant_closed']
    outcome: Literal['PREQUALIFIED', 'NOT_PREQUALIFIED']
    consultant_id: str
    language: Annotated[Optional[Literal['es', 'pt']], Field(...)]


class TraceThreadTaken(TraceEventBase):
    event_name: Literal['conversation.thread_taken']
    reason_code: Literal[
        'customer_requested_human',
        'out_of_scope',
        'language_unsupported',
        'model_output_invalid',
        'tool_failed',
        'policy_refer',
        'reply_forbidden',
    ]
    from_state: Literal['ai_active', 'human_active', 'ended']
    to_state: Literal['ai_active', 'human_active', 'ended']


class TraceAnalysisCompleted(TraceEventBase):
    event_name: Literal['analysis.completed']
    policy_version: Literal['alba-credit-v1']
    product: Literal['credit_card', 'personal_loan']
    outcome: Literal['PREQUALIFIED', 'NOT_PREQUALIFIED', 'REFER', 'NEEDS_INFO']
    deciding_rule: Literal['R01', 'R02', 'R03', 'R04', 'R05', 'R06', 'R09']
    rule_trace: List[RuleTraceStep]
    facts: List[Fact]
    language: Literal['es', 'pt']


class TracePrequalificationDecided(TraceEventBase):
    event_name: Literal['prequalification.decided']
    locale: Literal['es', 'pt']
    outcome: Literal['PREQUALIFIED', 'NOT_PREQUALIFIED']
    body: str
    decided_by: Literal['policy', 'consultant']


class TraceProcessStarted(TraceEventBase):
    event_name: Literal['process.started']
    process_key: Literal['credit_prequalification']
    customer_id: str


class TraceProcessStateChanged(TraceEventBase):
    event_name: Literal['process.state_changed']
    from_state: Literal['ai_active', 'human_active', 'ended']
    to_state: Literal['ai_active', 'human_active', 'ended']
    end_reason: Annotated[
        Optional[Literal['prequalified', 'not_prequalified']], Field(...)
    ]


class TraceProcessEnded(TraceEventBase):
    event_name: Literal['process.ended']
    end_reason: Literal['prequalified', 'not_prequalified']
    policy_version: Annotated[Optional[Literal['alba-credit-v1']], Field(...)]


class CaseTrace(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    process_id: UUID
    events: List[
        Union[
            TraceMessageReceived,
            TraceTurnClassified,
            TraceTemplateSent,
            TraceConsultantClosed,
            TraceThreadTaken,
            TraceAnalysisCompleted,
            TracePrequalificationDecided,
            TraceProcessStarted,
            TraceProcessStateChanged,
            TraceProcessEnded,
        ]
    ]


Role = Literal['customer', 'consultant']
ProcessState = Literal['ai_active', 'human_active', 'ended']
EndReason = Literal['prequalified', 'not_prequalified']
ProductKey = Literal['credit_card', 'personal_loan']
TemplateLocale = Literal['es', 'pt']
TurnLanguage = Literal['es', 'pt', 'other']
Outcome = Literal['PREQUALIFIED', 'NOT_PREQUALIFIED', 'REFER', 'NEEDS_INFO']
CloseOutcome = Literal['PREQUALIFIED', 'NOT_PREQUALIFIED']
IncomeCurrency = Literal['MXN', 'COP', 'ARS']
ReasonCode = Literal['customer_requested_human', 'out_of_scope', 'language_unsupported', 'model_output_invalid', 'tool_failed', 'policy_refer', 'reply_forbidden']
Intent = Literal['product_info', 'prequalify_card', 'prequalify_loan', 'confirm_prequalify', 'decline_prequalify', 'provide_income', 'human_request', 'out_of_scope', 'clarify', 'chit_chat']
TemplateId = Literal['needs_income', 'refer_notice', 'which_product', 'confirm_prequalify']
DecidedBy = Literal['policy', 'consultant']
RuleId = Literal['R01', 'R02', 'R03', 'R04', 'R05', 'R06', 'R09']
RuleTraceResult = Literal['passed', 'self_declared', 'PREQUALIFIED', 'NOT_PREQUALIFIED', 'REFER', 'NEEDS_INFO']
Actor = Literal['customer', 'consultant', 'system', 'rule']
MessageAuthor = Literal['customer', 'assistant', 'template']
PolicyVersion = Literal['alba-credit-v1']
ProcessKey = Literal['credit_prequalification']
EventName = Literal['conversation.message_received', 'conversation.turn_classified', 'conversation.template_sent', 'conversation.consultant_closed', 'conversation.thread_taken', 'analysis.completed', 'prequalification.decided', 'process.started', 'process.state_changed', 'process.ended']
